### ISSUE TITLE
Slack notifications for auditing issues

### ISSUE THREAD

**Issue by JanBednarik** [kiwicom/the-zoo#150]
It would be nice to have notifications about `NEW` or `REOPENED` auditing Issues sent to Slack channel specific to Service/team.

In addition our application security team would like to get notifications about `NEW` or `REOPENED` Issues from subset of kinds from all Services to one Slack channel.

cc @janmasarik

**Comment by janmasarik** [comment]
Internally tracked in https://gitlab.skypicker.com/platform/security/hub/issues/167

**Comment by aexvir** [comment]
Duplicate of this one https://gitlab.skypicker.com/platform/software/zoo/issues/231

**Comment by aexvir** [comment]
@bayotop started working on it. And I'll close https://github.com/kiwicom/the-zoo/issues/71 as this kind of is a duplicate of that one, but there are more comments here.

So I'll just mention the idea of also automatically opening GitLab issues in their repos for security stuff besides just the notifications about the issues status, as that was my main point in that one.

**Comment by aexvir** [comment]
@bayotop can we take over this? Or do you have progress here?
