### ISSUE TITLE
Support multiple environments per Service

### ISSUE THREAD

**Issue by aexvir** [kiwicom/the-zoo#166]
Services usually have multiple environments/stages, and the URLs for them aren't the same ones. Some services, like Sentry support easily differentiating between environments within the same UI.

We should add support for that in The Zoo, starting with just some basic, where we would have the possibility to store the same info multiple times per service, and just show some UI differentiating it

Suggested by dido

**Comment by paveldedik** [comment]
How do we do this? I have basically only this idea:

Create new model `Environment`, with foreign key to `Service`, the following fields could be moved from `Service`:

- slack_channel - not sure, but could be different for production vs staging, right?
- sentry_project
- rating_grade - Sentry related
- rating_reason - Sentry related
- sonarqube_project - not sure about this
- pagerduty_url - not sure, pagerduty makes probably only sense for production, but there can theoretically be more than one production environments
- dashboard_url - not sure about this as well
- docs_url - latest vs dev docs (makes more sense for libraries)
- service_url
- health_check_url

For `Library` model, we would have to create this `Environment` model as well.

Another way to do it is to have the `Environment` model store only the values different from `Service`/`Library`, but I don't like that very much.

Or do you have a different idea how to implement it @aexvir ?

**Comment by aexvir** [comment]
I don’t think the library needs different environments, as per definition is the context where it’s running, and libraries aren’t running somewhere.

As for the fields to be moved under the environment I think that only dashboard_url, service_url and healtch_check_url make sense.

Sentry is already able to differentiate between environments, and those should be under the same project, so the only feature we could consider here would be filtering the metrics per environment, but I think this doesn’t really need to be in the scope right now.

PagerDuty shouldn’t be on anything else than production and sonarqube is static code analysis, so environment agnostic as well.

Other than that looks good to me

**Comment by paveldedik** [comment]
Alright, thank you! I thought we want to have direct link to sentry environment for metrics and stuff as you mentioned. But that can be done later (either by moving the field or by adding something like `sentry_environment` to this new model).
