### ISSUE TITLE
Remove issues that no longer apply

### ISSUE THREAD

**Issue by aexvir** [kiwicom/the-zoo#19]
Checks can have logic that makes them not run if the it doesn't make sense to run it over the codebase. If there is any issue in the logic that determines if the check should run and the Issue is created there is no way to remove the issue after the logic has been fixed, besides doing it manually.

The runner should detect the checks that are no longer returning results and delete the related issues from the database.

**Comment by JanBednarik** [comment]
It can be solved by deleting Issues with old `last_check` date. There are three reasons why last check date is older than couple of hours - check has been removed, it's broken or does not apply to codebase anymore.

We can create and schedule cleanup task which will handle this. It should do (assuming that we run checks regularly every hour):
- delete all Issues with kind key not found in `KINDS` (removed checks)
- for each kind key: if there is no Issue with last check date newer than 2 hours => check is broken => report to Sentry
- for each kind key: if there is at least one Issue with last check date newer than 2 hours, then delete Issues with last check date older than 2 hours

**Comment by paveldedik** [comment]
Do we need to create a new scheduled task? My idea was to remove no longer relevant issues in the `zoo.repos.tasks.pull` task.

**Comment by JanBednarik** [comment]
`zoo.repos.tasks.pull` is run every hour for every repo and it has different purpose. This cleanup can be run like once a day. And it should be in `zoo.auditing.tasks`, because it's related to auditing Issues.

**Comment by paveldedik** [comment]
Sorry, I should have read your previous comment more carefully. What you are suggesting would probably work and I agree - it makes more sense to include that in a separate cleanup task. However, I'm mainly thinking about situations like:

1. there can be checks that yield results only under some conditions, e.g.
    ```python
    if 'python' in context.languages:
        yield context.Result(...)
    ```
    In such cases, it can happen that python is no longer used in a repository and nonrelevant issues remain in the DB.
2. issues of deleted checks should be removed from the database (basically your first bullet).

I believe both can be handled in the `runner` (which is called from the pull task).

**Comment by JanBednarik** [comment]
Your point 1. is covered by third bullet.

It should not be part of `runner`, because it's not used only on `pull` task, but also in API. Also it would unnecessarily complicate it. It's better to keep this cleanup logic separate if possible.
