### ISSUE TITLE
Add SonarQube linking to service

### ISSUE THREAD

**Issue by underyx** [kiwicom/the-zoo#22]
- [x] Add a field for sonarqube URL
- [x] Add a periodic task that finds the sonarqube URLs

**Comment by paveldedik** [comment]
@underyx what do you mean by "Add a periodic task that finds the sonarqube URLs"?

**Comment by underyx** [comment]
We don't want people to have to manually add the link to sonarqube (no one will do that on their own volition.)

So we should use the sonarqube API to get all the projects that are on it, and automatically link them to the zoo services.
