### ISSUE TITLE
Add filter before starting Audit

### ISSUE THREAD

**Issue by maroshmka** [kiwicom/the-zoo#23]
Before starting Audit, there can be a filter that will allow you to run audit only for needed repos.
Can include some handy shortcuts like `all`, `all:<gitlab-group>` (`all:django-team`) or just simple checkboxes for each repos (imho no need to have complex filtering options for now).

It may be a simpler version of https://github.com/kiwicom/the-zoo/issues/9, when you do not need to audit all repos. 

What do you think ?

**Comment by aexvir** [comment]
Are you talking about the Auditing Overview UI? As a temporary solution I can easily make only the filtering available and not load anything until there have been some filters, which should improve its speed as it won't have to load all the data at once.

But the solution is definitely https://github.com/kiwicom/the-zoo/issues/14

If you are talking about CLI... depends if it's a really common use case. Django allows filtering the Repository objects with whatever criteria you want, and then is just a matter of calling the `pull` task on each one.

**Comment by maroshmka** [comment]
Yes I meant the UI.

IMHO, pagination without filter solves it only partially as you still needs to look on the next pages to find something. Combination of both should do it :)

**Comment by aexvir** [comment]
Won't be done, the main issue will be solved by redesigning the overview to not have to include all the information we currently have.
