### ISSUE TITLE
Ditch prance in favour of json schema

### ISSUE THREAD

**Issue by aexvir** [kiwicom/the-zoo#271]
Prance is annoying to maintain, really strict and it requires dependencyes like PyICU, which are again annoying to install.

Schemathesis for example uses it and it seems to work quite well

https://github.com/kiwicom/schemathesis/blob/master/src/schemathesis/schemas.py#L76

**Comment by Stranger6667** [comment]
For the record - the current implementation in Schemathesis will fail to resolve recursive schemas, not sure if `prance` can handle it and how popular such schemas are

**Comment by aexvir** [comment]
We ended up keeping `prance`, but removing the `PyICU` dependency. Closing this...
