### ISSUE TITLE
Add support for explicit openapi.json path

### ISSUE THREAD

**Issue by msladecek** [kiwicom/the-zoo#292]
# Context
Zoo has a feature where it serves a swagger-ui page to the user based on openapi definitions of a particular service.

This definition is obtained by scanning the service's repository for yaml/json files and composing them into a single json object to be accepted by the swagger-ui app.

When Zoo is unable to find/build the specification it displays this popup to the user:

>API Schema not available
The repository either doesn't contain any OpenAPI definitions, or the ones available couldn't be parsed correctly

# Problem

The current way of obtaining the api specification creates an unnecessary pressure on the service's maintainers to structure their spec files in a certain way, in order to be compatible with Zoo.

Some spec building approaches, such as templating or using a framework which assembles the spec from native data structures are, by their nature, incompatible with Zoo because the spec in it's final form only exists after the service has been deployed, and cannot be easily obtained just by scanning the repository.

# Solution proposal
Give the user an option to explicitly specify the url of the final `openapi.json`, similarly to the way urls to documentation and pagerduty can be specified.

It is the de-facto standard to serve the specification file on one of these paths:
```
{api_root_url}/openapi.json
{api_root_url}/openapi.yml
{api_root_url}/swagger.json
etc...
```

In addition/as an alternative to the explicit configuration, these paths could be scanned as a fallback.

Scanning the repo itself would only remain as a last resort.

**Comment by aexvir** [comment]
Done via https://github.com/kiwicom/the-zoo/commit/d7f3d95c59b404cf014f365915a8f09b833372c0
