### ISSUE TITLE
Allow multiple service URLs

### ISSUE THREAD

**Issue by aexvir** [kiwicom/the-zoo#47]
The immediate use case we got reported mentioned staging envs, but there could be some use case where the service would benefit from multiple endpoints, like some common service that is running in different stacks.

**Comment by paveldedik** [comment]
Related to https://github.com/kiwicom/the-zoo/issues/166

It will make the form for creating/updating services a bit more complicated - there's already going to be a choice to add an environment. Now, for each environment, user will be able to add multiple service URLs.

I'm not absolutely happy that the form will get even more complicated with this, but don't have any other solution.

**Comment by aexvir** [comment]
This can be solved in a couple ways, one way would be to have like a `+` button at the end of the form, that would allow to create a new inner form for each environment, `django` supports this behaviour via [formsets](https://docs.djangoproject.com/en/2.2/topics/forms/formsets/)

Or we could also make the environments configurable in a new view. With a single form for adding/editing an environment. In that case we could be a bit "smart" and keep the fields we want to move to the environment in the current form, and "magically" create that environment with a generic name like `Default`, and let the users change it afterwards. This is more or less the approach that Sentry follows, for example.

Ideally I think we'd like to have both? In the way that appending forms with environments to the initial form could help someone adding many services (although ORM/API could be a better option), and the second one it's needed for sure, as mistakes can happen and environments need to be editable/removable/addable.

So I'd go for the second option, and if it's really a pain we can think of making something smarter in the initial form. What do you think @paveldedik ?

**Comment by paveldedik** [comment]
Thanks. Yep, I know about formsets, I think the way to go is [inline_formset](https://docs.djangoproject.com/en/2.2/topics/forms/modelforms/#django.forms.models.BaseInlineFormSet). I would do it like this: by default, no environment needs to be set, it will be named "default". But there will be a button to add/edit environments. Is this what you are suggesting or am I misunderstanding?

Anyway, my comment was about service URLs, which add another layer here - another `+` button in each environment, to add more service URLs. That's why I was saying that it will be a bit more complicated.

**Comment by aexvir** [comment]
> Thanks. Yep, I know about formsets, I think the way to go is inline_formset. I would do it like this: by default, no environment needs to be set, it will be named "default". But there will be a button to add/edit environments. Is this what you are suggesting or am I misunderstanding?

Yep, that's it 🙂 

> Anyway, my comment was about service URLs, which add another layer here - another + button in each environment, to add more service URLs. That's why I was saying that it will be a bit more complicated.

True, I got too hooked to the related issue that I didn't realize that this was about the service URLs. Yep, I agree that maybe nesting formsets is not going to be the most awesome thing to do... but at the end it seems like the correct way to do? 

The alternative would be to do all this in the client side and just craft a backend payload that would allow creating all the model instances needed. I think that at the current scale it's still manageable, but this might be required if we expand it even further.
