### ISSUE TITLE
List and describe APIs

### ISSUE THREAD

**Issue by photonbit** [kiwicom/the-zoo#59]
Different species have different ways of communicating with each other, so in an environment with many services talking between them it could be beneficial to have the list of APIs associated with services, among some information to help kickstart talking to them, as 

- scope of the API
- specs and or documentation links
- staging / sandbox / production links
- authentication mechanisms
- pagination format
- versioning pattern
- deviations from standards or common practices

**Comment by underyx** [comment]
I wanted to scrape most of this info from OpenAPI schemata, if any are provided 😇

**Comment by aexvir** [comment]
Suggestion from @martin-sucha 

Collect Swagger schema definition YAML and host it in Swagger UI for each service.

**Comment by fallion** [comment]
Can I provide help here?
