### ISSUE TITLE
Create new models to hold this information

### ISSUE THREAD

**Issue by aexvir** [kiwicom/the-zoo#89]
We'll need to add new models to support this structure, and get rid of the current `Datacenter` which is only a static list of strings currently.

**Comment by paveldedik** [comment]
As far as I understand (I'm not sure I'm using correct terminology everywhere, sorry for that, I hope it's clear anyway):

* each Zoo service can be theoretically deployed to several datacenters (= Amazon, Google, etc.), not sure if we have such services in Zoo, but in my model, I'm assuming it's possible
* Rancher has Stacks which usually represent one Zoo service, but we cannot relay on that, that's just Rancher's way of scoping things, we only care about Rancher services. Not sure, how this works in GCP, but we also probably care only about GCP services
* One Zoo service has usually multiple Rancher/GCP services, we link Zoo service to Rancher/GCP services using docer image url and Gitlab repo url
* Theoretically we even can have a Zoo service with multiple services in Rancher - one handling requests from zoo1.example.com and another one from zoo2.example.com, so there will be two URLs associated with one Zoo service

I think the following model could work (but it's possible I'm missing some important information):

**Datacenter**
- `id`
- `name`
- `region`
- note: we can decide removing this model and use only strings in `ServiceDatacenter`

**ServiceDatacenter**
- `id`
- `service_id` - ID of the Zoo service
- `datacenter_id` - ID of the DataCenter
- note: with this model, it's possible to have one Zoo service associated with multiple datacenters

**ServiceDatacenterMember**
- `id`
- `service_datacenter_id` - ID of ServiceDatacenter
- `name` or/and `email`
- note: we could also add `user_id` field which would be a foreign key to `user` table, not sure it's useful

**ServiceDatacenterService** (wierd name, let's focus on names later when we agree on the structure)
- `id`
- `service_datacenter_id` - ID of ServiceDatacenter
- `name` - name of the service
- `public_url` - URL of the service, can be empty

**Comment by aexvir** [comment]
> each Zoo service can be theoretically deployed to several datacenters (= Amazon, Google, etc.), not sure if we have such services in Zoo, but in my model, I'm assuming it's possible

Yep, that's true and it doesn't even have to be in different providers. There can be multiple datacenters (regions / zones) in the same provider.

> Rancher has Stacks which usually represent one Zoo service, but we cannot relay on that, that's just Rancher's way of scoping things, we only care about Rancher services. Not sure, how this works in GCP, but we also probably care only about GCP services

Yes, the approach should be to build this tree from the bottom, so starting from each provider and linking it to our services. 

> One Zoo service has usually multiple Rancher/GCP services, we link Zoo service to Rancher/GCP services using docer image url and Gitlab repo url

Technically... true. Although the approach should be a little bit more generic as we just gather the members and some more metadata from the providers. One approach could be to just have all the GCP/Rancher services linked to the Zoo service and at the time of returning the data just "merge" the members for example.

> Theoretically we even can have a Zoo service with multiple services in Rancher - one handling requests from zoo1.example.com and another one from zoo2.example.com, so there will be two URLs associated with one Zoo service

Yep, and all those URLS should be gathered in the service model, replacing our current single field.

**Comment by aexvir** [comment]
So far it's fine but I think you need to specify more fields on the models. Those models aren't referencing any of the properties we want to keep track of.

**Comment by paveldedik** [comment]
Thank you for the review. What are the properties we want to keep track of? I thought that at first, we want to:

- get each service's URL- the `ServiceDatacenterService.public_url`
- get list of members - `ServiceDatacenterMember`

I realize that some fields may be missing (like deployed image url), but what other fields do you mean?

**Comment by aexvir** [comment]
It seems I didn't check the models properly, sorry about that. I see that the info is already there.

In that case, now I'm not sure about the role of the `ServiceDatacenterService` model. What is it supposed to hold? The different components of a service? Like in the case of Sentry the `web` and the `workers`?

In that case `ServiceDatacenterService.public_url` could still be more than one URL, otherwise it could be considered as something that just holds an `endpoint`, but I don't see that much use for that separation currently.

**Comment by paveldedik** [comment]
Yes, in the case of Sentry, it would be `web`, `workers`, etc. If we don't have this, which component (Rancher service) are we going to link with the Zoo service? I mean, it makes sense to link them all, right? Not all services handle requests though, the public URL would be empty in most cases, but we may decide to store other metadata for each component at some point.

But it may not be that useful and as you mentioned, the `public_url` still could be more than one URL. So  we could create something like this instead:

**ServiceDatacenterMetadata**
- `id`
- `service_datacenter_id` - ID of ServiceDatacenter
- `key` - e.g. `public_url`
- `value` - value for the given key, e.g. `zoo.example.com`

Which could store multiple values for any kind of `key`. But it's not exactly the best practice. There are other options:

**ServiceDatacenterMetadata**
- `id`
- `service_datacenter_id` - ID of ServiceDatacenter
- `urls` - list of URLs in e.g. JSON
- `members` - list of members in e.g. JSON
- `components` - names of components like `web`, etc.

So what do you think, which approach would work best here?

**Comment by aexvir** [comment]
Also done
